In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
df

A  B
0  1  4
1  2  5
2  3  6

In [4]:
type(df)

pandas.core.frame.DataFrame

In [5]:
df_numpy = df.to_numpy()
df_numpy

array([[1, 4],
       [2, 5],
       [3, 6]])

In [6]:
type(df_numpy)

numpy.ndarray

In [7]:
# pandas.DataFrame.values method (not recommended):

df = pd.DataFrame({"A": [1, 2, 3], "B": [4, 5, 6]})
df

A  B
0  1  4
1  2  5
2  3  6

In [8]:
df_values = df.values
df_values

array([[1, 4],
       [2, 5],
       [3, 6]])

In [9]:
type(df_values)

numpy.ndarray

In [10]:
df = pd.DataFrame({"A": [10, 20, 30, 40, 50], "B": [60, 70, 80, 90, 100]})
df

A    B
0  10   60
1  20   70
2  30   80
3  40   90
4  50  100

In [11]:
A_array = df["A"].to_numpy()  # only a single column
A_array

array([10, 20, 30, 40, 50])