In [2]:
import numpy as np

In [3]:
np.greater([4,2],[2,2])

array([ True, False])

In [8]:
### The > operator can be used as a shorthand for np.greater on ndarrays !!! ###

a = np.array([4, 2, -3])
b = np.array([2, 2, -10])
a > b

array([ True, False, False])

In [5]:
np.less([1, 2], [2, 2])

array([ True, False])

In [7]:
### The < operator can be used as a shorthand for np.less on ndarrays !!! ###

a = np.array([1, 2, 7])
b = np.array([2, 2, 5])
a < b

array([ True, False, False])