In [14]:
import numpy as np
import pandas as pd
from scipy.signal import argrelextrema

In [15]:
df = pd.DataFrame({"A": [8, 9, 10, 20, 80, 40, 50, 55, 56, 57, 58], "B": [60, 70, 150, 10, 100, 65, 66, 67, 68, 69, 70]})
df

A    B
0    8   60
1    9   70
2   10  150
3   20   10
4   80  100
5   40   65
6   50   66
7   55   67
8   56   68
9   57   69
10  58   70

In [16]:
A_ndarray = df["A"].to_numpy()
A_ndarray

# Convert column "A" to numpy ndarray.

array([ 8,  9, 10, 20, 80, 40, 50, 55, 56, 57, 58])

In [17]:
A_extrema_max = argrelextrema(A_ndarray, np.greater, order = 3)
A_extrema_max

# Output is a tuple object, first element is the index of maxima which is a numpy array.

(array([4]),)

In [18]:
A_extrema_max[0]  # This is the index of the maxima point.

array([4])

In [19]:
type(A_extrema_max[0])  # First element is a numpy array.

numpy.ndarray

In [20]:
A_ndarray[A_extrema_max[0]]

# Insert index into the ndarray to find maxima value. Maxima value is 80.

array([80])

In [22]:
B_ndarray = df["B"].to_numpy()
B_ndarray

array([ 60,  70, 150,  10, 100,  65,  66,  67,  68,  69,  70])

In [23]:
B_extrema_min = argrelextrema(B_ndarray, np.less, order = 3)
B_extrema_min[0]

# First element of the output is the index of the minima.

array([3])

In [24]:
B_ndarray[B_extrema_min[0]]

# Insert index into the ndarray to find minima value. Minima value is 10.

array([10])